version: '3.7'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: mlflowdb
    ports:
      - "5432:5432"
    volumes:
      - "./pg-data:/var/lib/postgresql/data"
